### ISSUE TITLE
Menu links don't result in sharable URLS

### ISSUE THREAD

**Issue by mribbons** [socketsupply/sockets.sh#105]
Using the side menu to navigate, the browser URL doesn't change from https://sockets.sh

If we click `Troubleshooting -> Windows`, I would expect the URL to change to 

`https://sockets.sh/#troubleshooting-windows` or something unique.

Also, is the site indexable?

**Comment by heapwolf** [comment]
We're shutting down this site and will redirect it to the main site. Deep linking is still a valid request though.

**Comment by heapwolf** [comment]
Added in new docs.
