### ISSUE TITLE
broken link — `/mobile`

### ISSUE THREAD

**Issue by nichoth** [socketsupply/sockets.sh#35]
https://sockets.sh/mobile/

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5776508/194904078-3813ef19-aa1a-465f-bf3a-86bb2ecdc4ad.png">

**Comment by nichoth** [comment]
This link is in the page https://sockets.sh/guides/

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5776508/194904551-03213e43-dffc-40b4-ba3a-fdc52bd3c9d4.png">

**Comment by lamiazar** [comment]
I just tested this and yes, it is broken .
