### ISSUE TITLE
`android` table is empty in the `https://sockets.sh/config/` page

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/sockets.sh#45]
![Screen Shot 2022-11-14 at 09 35 39](https://user-images.githubusercontent.com/79177582/201687080-a430922e-899e-4965-bbd1-e5c27169cf64.png)

![Screen Shot 2022-11-14 at 09 34 35](https://user-images.githubusercontent.com/79177582/201686859-9a8051dc-20d0-46b1-99e5-de18fa16594d.png)

![Screen Shot 2022-11-14 at 08 36 13](https://user-images.githubusercontent.com/79177582/201674077-ce121bda-a1b3-4737-982c-b6f478c81cee.png)
  

is this `wip`? or the table should be empty ?

**Comment by chicoxyzzy** [comment]
it's not documented yet

**Comment by lamiazar** [comment]
This page was updated and the `android` table doesn't exist anymore.
