### ISSUE TITLE
Repeated text in the `API ` under `Buffer`

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/sockets.sh#58]
The same text is repeated multiple times like `undefined` and `Buffer`
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/79177582/212398460-4fe6ef4b-ded2-455a-887d-c214201b6f8f.PNG">

**Comment by chicoxyzzy** [comment]
we decided to remove this vendor module from the documentation
cc @heapwolf

**Comment by lamiazar** [comment]
@chicoxyzzy The links (on the left side) seem broken, I opened another issue here #57

**Comment by lamiazar** [comment]
I'm checking the `docs` again and, this issue is resolved.
