### ISSUE TITLE
add a side bar to the `TOC` on mobile

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/sockets.sh#77]
We decided to hide the table of contents on mobile, but one of the users was complaining that he can't scroll the `TOC` on mobile (he was viewing the docs on his phone using `Desktop site`). I can reproduce the issue on my phone by using the `Desktop site`

![Screenshot_20230213_092432_Chrome](https://user-images.githubusercontent.com/79177582/218485476-0fd04f86-a60a-4d9d-bf6b-9784bac32dd8.jpg)

----> This is something we can consider in the near future.

**Comment by heapwolf** [comment]
wait, someone was complaining that the desktop version of the site doesnt work on mobile?

**Comment by lamiazar** [comment]
> wait, someone was complaining that the desktop version of the site doesnt work on mobile?
 this was a few weeks ago , he was viewing the `docs` on mobile using `desktop site` and his issue was that after he opened all the subfolders in the `toc` on the left he ran out of vertical space, he couldn't scroll.

**Comment by lamiazar** [comment]
I just tested the docs on mobile using `desktop site` , I opened all the subfolders and can scroll and see all the content.
![Screenshot_20230307_084721_Chrome](https://user-images.githubusercontent.com/79177582/223442100-9c899bce-fb56-4272-97c6-6ce482d3973e.jpg)
